# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_staf',
            new_name='is_staff',
        ),
    ]
